name: quickmath
description: Maths Quiz Game
version: 1.0.0+1

environment:
   sdk: '>=2.1.0 <3.0.0'

dependencies:
   flutter:
      sdk: flutter
   cupertino_icons: ^0.1.2
   provider: ^4.0.4
   localstorage: ^3.0.1+4
   cloud_firestore: ^0.13.4
   firebase_database: ^3.1.3
   google_sign_in: ^4.0.6
   http: ^0.12.0+3
   firebase_auth: ^0.11.1+12
   ant_icons: ^1.0.0
   after_layout: ^1.0.7+2
   intl: ^0.16.1
   share: ^0.6.3+5
   url_launcher: ^5.4.1

dev_dependencies:
   flutter_test:
      sdk: flutter
flutter:
   uses-material-design: true
   assets:
      - assets/res/

   fonts:
      - family: JetBrain
        fonts:
           - asset: assets/fonts/JetBrainsMono.ttf
